### ISSUE TITLE
0.1.0 Release Checklist

### ISSUE THREAD

**Issue by iwoplaza** [software-mansion/TypeGPU#180]
- [x] Verify that it works on React Native
  - [x] Install and use TypeGPU on React Native
  - [x] Figure out why the device has to be passed in explicitly.
  - [ ] (Optional?) Create a repository for an example app that uses React Native WebGPU and TypeGPU.
- [x] Write release notes.
- [x] Make the webpage indexable
- [x] Release the 0.1.0 package
- [x] Update StackBlitz example to use the new version
- [x] Post on Twitter
